<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
  /*
In JavaScript, try...catch is used for error handling. It allows you to handle exceptions gracefully,
 so your code can handle errors without completely stopping execution.
Basic Structure of try...catch
The try...catch block has the following structure:

try {
    // Code that may throw an error
} catch (error) {
    // Code to handle the error
}
try block: Contains code that you want to test for errors. If an error occurs in this block,
           the code execution immediately jumps to the catch block.
catch block:Runs only if an error occurs in the try block. The catch block receives the error object, which
             contains details about the error.

  */
 // benefit od using this that the rest of the code still run usually if an error occur then the code exection stops but using this 
 // doesnot effect the rest of the code 
 try{
   console.log(p);
 // try krle ek bar
}
catch(error){ // agr fir bhi error aata h to console m throw mt kr simply usko likh de
    console.log("balle balle ") // or simply can write console.log(error) 
}
 // try can only work for the sync code but didnot work properly with the async code like settimeout 
 try{
    setTimeout(()=>{ 
    //   console.log(aalu gobhi) // here the js will not handle the error as it is an async code and it will throw an error 
    },1000)
 }
 catch(error){
    console.log("bacha le bhai") 
 }
 // but if we put it inside the settimeout then it will handle it properly

    setTimeout(() => {
        try{
            console.log(aurr) // this will handle the error perfectly  as it is inside the settimeout 
        }
        catch(error){
            console.log(error)
        }
       
         
    },2000);
    //                                                    ERROR OBJECT 
    /*
    The Error object in JavaScript represents an error that occurs during the execution of code. When an error occurs,
     JavaScript creates an instance of this Error object, which contains information about the error. 
     You can also create your own Error objects to throw custom errors.
     asic syntax of the custom error 
     let error = new Error("This is an error message.");
      Here, "This is an error message." is the message passed to the Error object, which helps identify or describe the issue.
     * /
 
try {
    anish
} catch (error) {
    console.log(error.message)  //  this will give the message of the error 
    console.log(error.name) // this will give the name of the of the error 
}
</script>
</body>
</html>